---
name: eliud_pkg_feed_model
description: eliud_pkg_feed is a package to provide a social media feed functionality
  to your eliud app. More info at https://eliud.io
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_pkg_feed
version: 1.1.5+7
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  bloc: ^8.1.2
  chips_input: ^0.1.0
  cloud_firestore: ^4.12.2
  collection: ^1.17.2
  eliud_core:
    path: ../eliud_core
  eliud_core_main:
    path: ../eliud_core_main
  eliud_core_helpers:
    path: ../eliud_core_helpers
  eliud_core_model:
    path: ../eliud_core_model
  eliud_pkg_follow: 
    path: ../eliud_pkg_follow
  eliud_pkg_medium:
    path: ../eliud_pkg_medium
  eliud_pkg_membership:
    path: ../eliud_pkg_membership
  eliud_pkg_notifications:
    path: ../eliud_pkg_notifications
  eliud_pkg_text:
    path: ../eliud_pkg_text
  eliud_pkg_etc:
    path: ../eliud_pkg_etc
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  meta: ^1.9.1
  pointer_interceptor: ^0.9.3+6
  tuple: ^2.0.2
  flutter:
    sdk: flutter
dev_dependencies:
  build_runner: ^2.4.6
  eliud_generator:
    path: ../eliud_generator
  lints: ^3.0.0
flutter:
  uses-material-design: true
platforms:
  android: null
  ios: null
  web: null
